export const CATEGORIES_ACTIONS = {
	FETCH_CATEGORIES_START: 'categories/FETCH_CATEGORIES_START',
	FETCH_CATEGORIES_SUCCESS: 'categories/FETCH_CATEGORIES_SUCCESS',
	FETCH_CATEGORIES_ERROR: 'categories/FETCH_CATEGORIES_ERROR',
	SET_DIRECTORIES: 'categories/SET_DIRECTORIES',
};
